##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

backend:
  name: git-gateway

# local_backend: true

##
##

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "news"
    label: "News"
    folder: "/content/news"
    create: true
    slug: "{{slug}}"
    format: toml-frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    format: toml-frontmatter
    files:
      - name: "contact"
        label: "Contact Page"
        file: "/content/about/_index.md"
        fields:
          - {label: "Form Title", name: "extra.form_title", widget: string}
          - {label: "Form Description", name: "extra.form_description", widget: string}
          - {label: "Form Email Input Label", name: "extra.form_email_input_label", widget: string}
          - {label: "Form Submit Button Text", name: "extra.form_submit_button_text", widget: string}
