##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

backend:
  name: git-gateway
  branch: main

# local_backend: true

##
##

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    format: toml-frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", format: "YYYY-MM-DD"}
      - { label: "Body", name: "body", widget: "markdown" }
      - name: "extra"
        label: "Extra Fields"
        widget: object
        fields:
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - {label: "Contact Us Header", name: "contact_header", widget: string}
          - {label: "Contact Us Call-to-Action Button Text", name: "contact_cta_button_text", widget: string}
  - name: "case-studies"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    slug: "{{slug}}"
    format: toml-frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", format: "YYYY-MM-DD"}
      - { label: "Body", name: "body", widget: "markdown" }
      - name: "extra"
        label: "Extra Fields"
        widget: object
        fields:
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - {label: "Contact Us Header", name: "contact_header", widget: string}
          - {label: "Contact Us Call-to-Action Button Text", name: "contact_cta_button_text", widget: string}
  - name: "pages"
    label: "Pages"
    format: toml-frontmatter
    editor:
      preview: false
    files:
      - name: "home"
        label: "Landing Page"
        file: "content/_index.md"
        fields:
          - name: "extra"
            label: "Editable fields"
            widget: object
            fields:
              - {label: "Hero Title", name: "hero_title", widget: string}
              - {label: "Hero Description", name: "hero_description", widget: text}
              - {label: "Hero Call-to-Action Button Text", name: "hero_cta_button_text", widget: string}
              - {label: "Introduction Header", name: "intro_header", widget: string}
              - {label: "Introduction Image Path", name: "intro_image_path", widget: image, allow_multiple: false}
              - {label: "Introduction Paragraph #1", name: "intro_paragraph0", widget: text}
              - {label: "Introduction Paragraph #2", name: "intro_paragraph1", widget: text}
              - {label: "Introduction Call-to-Action Button Text", name: "intro_cta_button_text", widget: string}
              - {label: "Flowchart Image Path", name: "flowchart_image_path", widget: image, allow_multiple: false}
              - {label: "Flowchart Alternate Text", name: "flowchart_alt_text", widget: text}
              - {label: "Benefits Header", name: "benefits_header", widget: string}
              - label: "Benefits"
                name: "benefits"
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: string}
                  - {label: "Description", name: "description", widget: text}
              - {label: "About Us Header", name: "about_header", widget: string}
              - {label: "About Us Description", name: "about_description", widget: text}
              - {label: "About Us Call-to-Action Button Text", name: "about_cta_button_text", widget: string}
              - {label: "News Call-to-Action Button Text", name: "news_cta_button_text", widget: string}
              - {label: "Contact Us Header", name: "contact_header", widget: string}
              - {label: "Contact Us Call-to-Action Button Text", name: "contact_cta_button_text", widget: string}
      - name: "contact"
        label: "Contact Page"
        file: "content/contact/_index.md"
        fields:
          - name: "extra"
            label: "Editable fields"
            widget: object
            fields:
              - {label: "Form Title", name: "form_title", widget: string}
              - {label: "Form Description", name: "form_description", widget: string}
              - {label: "Form Email Input Label", name: "form_email_input_label", widget: string}
              - {label: "Form Name Input Label", name: "form_name_input_label", widget: string}
              - {label: "Form Position Input Label", name: "form_position_input_label", widget: string}
              - {label: "Form Message Subject Input Label", name: "form_subject_input_label", widget: string}
              - {label: "Form Message Content Input Label", name: "form_message_input_label", widget: string}
              - {label: "Form Pitch Download Checkbox Label", name: "form_pitch_checkbox_label", widget: string}
              - {label: "Form Submit Button Text", name: "form_submit_button_text", widget: string}
              - {label: "Form Pitch PDF Download URL", name: "form_pitch_pdf_url", widget: string}
      - name: "about"
        label: "About Us Page"
        file: "content/about/_index.md"
        fields:
          - name: "extra"
            label: "Editable fields"
            widget: object
            fields:
              - {label: "Story Header", name: "story_header", widget: string}
              - label: "Story Paragraphs"
                name: "story_paragraphs"
                widget: list
                allow_add: true
                field: {label: "content", name: "content", widget: text}
              - label: "Story Signature"
                name: "story_signature"
                widget: object
                fields:
                  - {label: "Signature Name", name: "name", widget: string}
                  - {label: "Signature Caption", name: "caption", widget: string}
              - {label: "History Header", name: "history_header", widget: string}
              - label: "History Paragraphs"
                name: "history_paragraphs"
                widget: list
                allow_add: true
                field: {label: "content", name: "content", widget: text}
              - {label: "Problem Header", name: "problem_header", widget: string}
              - label: "Problem Paragraphs"
                name: "problem_paragraphs"
                widget: list
                allow_add: true
                field: {label: "content", name: "content", widget: text}
              - {label: "Vision Header", name: "vision_header", widget: string}
              - label: "Vision Paragraphs"
                name: "vision_paragraphs"
                widget: list
                allow_add: true
                field: {label: "content", name: "content", widget: text}
              - {label: "Values Header", name: "values_header", widget: string}
              - label: "Values"
                name: "values"
                widget: list
                allow_add: true
                fields:
                  - {label: "Value Title", name: "title", widget: string}
                  - {label: "Value Description", name: "description", widget: text}
              - {label: "Team Header", name: "team_header", widget: string}
              - label: "team"
                name: "team"
                widget: list
                allow_add: true
                summary: "{{fields.name}} ({{fields.title}})"
                fields:
                  - {label: "Member Profile Photo", name: "photo_path", widget: image, allow_multiple: false, required: false}
                  - {label: "Member Name", name: "name", widget: string}
                  - {label: "Member Title", name: "title", widget: string}
                  - {label: "Member Bio", name: "bio", widget: text, required: false}
